// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dildrtbecbauiabyqfut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbGRydGJlY2JhdWlhYnlxZnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Njg0NzMsImV4cCI6MjA1OTA0NDQ3M30.rwnJHfmAaisAYpoQxjYo0p4ooESVXLfdHIZCjlA63Bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);